//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GidraSIM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaseProcedureParameterNames
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BaseProcedureParameterNames()
        {
            this.ProceduresParameters = new HashSet<ProceduresParameters>();
        }
    
        public int BaseProcedureParameterNameId { get; set; }
        public int BaseProcedureId { get; set; }
        public string Name { get; set; }
    
        public virtual BaseProcedures BaseProcedures { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProceduresParameters> ProceduresParameters { get; set; }
    }
}
