//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GidraSIM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Processes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Processes()
        {
            this.Procedures = new HashSet<Procedures>();
        }
    
        public int ProcessId { get; set; }
        public int ProcessNameId { get; set; }
        public System.DateTime TotalTime { get; set; }
        public decimal TotalPrice { get; set; }
    
        public virtual ProcessNames ProcessNames { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Procedures> Procedures { get; set; }
    }
}
