//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GidraSIM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProceduresResources
    {
        public int ProcedureResourceId { get; set; }
        public int ResourceId { get; set; }
        public int ProcedureId { get; set; }
    
        public virtual Procedures Procedures { get; set; }
        public virtual Resources Resources { get; set; }
    }
}
