//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GidraSIM.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceParameters
    {
        public int ResourceParameterId { get; set; }
        public int ResourceParameterNameId { get; set; }
        public int ResourceId { get; set; }
        public Nullable<double> Value { get; set; }
    
        public virtual ResourceParameterNames ResourceParameterNames { get; set; }
        public virtual Resources Resources { get; set; }
    }
}
